### ISSUE TITLE
As a user I want to forward messages

### ISSUE THREAD

**Issue by Delight-Fela-Steve** [zurichat/zc_plugin_dm#305]
return json of forwarded message, showing forward=true and forwarded_to=user/list of users

**Comment by itz-salemm** [comment]
Working on this

**Comment by itz-salemm** [comment]
Displays a JSON response of forwarded messages
Live Link: https://dm.zuri.chat/api/forwardMessages

Slack Username: itz_salemm
GitHub Username: itz-salemm
